version: 1.0.{build}
branches:
  only: master
skip_tags: true
image: Visual Studio 2015
configuration: Debug
platform: x64
environment:
    qt: 5.8
    mode: release
    QTDIR: C:\Qt\5.8\msvc2015_64
init:
  - set vcarch=amd64
  - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" amd64
  - echo NUMBER_OF_PROCESSORS=%NUMBER_OF_PROCESSORS%
  - echo PROCESSOR_IDENTIFIER=%PROCESSOR_IDENTIFIER%
  - echo QTDIR=%QTDIR%
install:
  - cmd: set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%
  - cmd: set PATH=%QTDIR%\bin;%PATH%
  - cmd: echo %PATH%
  - cmd: mklink /j C:\Qt\Qt5.8.0 C:\Qt
build:
  parallel: true
  verbosity: minimal
