version: 1.0.{build}
configuration: Debug
platform: x64
os: Visual Studio 2015
environment:
  QTDIR: C:\Qt\5.6\msvc2015_64_opengl
install:
  - set PATH=%PATH%;%QTDIR%\bin
  #- mklink /j C:\Qt\Qt5.4.2 C:\Qt
build:
  parallel: true
  verbosity: minimal
