version: 1.0.{build}
branches:
  only: master
skip_tags: true
#os: Visual Studio 2015
configuration: Debug
platform: x64
environment:
  QTDIR: C:\Qt\5.8\msvc2015_64_opengl
  cname: Win64-VS2015
  VSVER: 14.0
  PT: v140
install:
  - set PATH=%PATH%;%QTDIR%\bin
  #- mklink /j C:\Qt\Qt5.8.0 C:\Qt
build:
  parallel: true
  verbosity: minimal
